### ISSUE TITLE
Kwok Stage Configs are not in expectation

### ISSUE THREAD

**Issue by mingyuanzhu** [kubernetes-sigs/kwok#1002]
### How to use it?

- [ ] kwok
- [X] kwokctl --runtime=docker (default runtime)
- [ ] kwokctl --runtime=binary
- [ ] kwokctl --runtime=nerdctl
- [ ] kwokctl --runtime=kind

### What happened?

Just applied the general folder (https://github.com/kubernetes-sigs/kwok/tree/main/kustomize/stage/pod/general) stage configs but caused the pod status from running -> containerCreating -> running
![Z7Bg1fdUJx](https://github.com/kubernetes-sigs/kwok/assets/6222056/1a92c2df-2ea3-4779-8e84-30f60ef4b031)

### What did you expect to happen?

I hope the status does not change to containerCreating after running.

### How can we reproduce it (as minimally and precisely as possible)?

I just the kwok 4.0.0 and apply the general stages config (https://github.com/kubernetes-sigs/kwok/tree/main/kustomize/stage/pod/general)

### Kwok version

<details>

```console
$ kwok --version
kwok version v0.4.0 go1.20.7 (linux/amd64)

$ kwokctl --version
kwokctl version v0.4.0 go1.21.0 (linux/amd64)
```

</details>

### OS version

<details>
```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

# On Darwin:
$ uname -a
Linux n199-192-082 5.4.143.bsk.8-amd64 #5.4.143.bsk.8 SMP Debian 5.4.143.bsk.8 Wed Jul 20 08:43:36 UTC  x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

**Comment by mingyuanzhu** [comment]
@wzshiming Thanks a lot if you can help to check

**Comment by wzshiming** [comment]
Thank you for your feedback.
Although this is still experimental, there is no test coverage that looks like the expected behavior changes.

I plan to refine it in this release.

**Comment by wzshiming** [comment]
This has been fixed, feel free to open it if there are still issues

/close
