### ISSUE TITLE
Support helm charts in kwok

### ISSUE THREAD

**Issue by yuanchen8911** [kubernetes-sigs/kwok#1029]
### What would you like to be added?

It would be great if KWOK could support Helm charts. I had a brief discussion with @wzshiming on Slack, and here's a summary.

The main issue arises from the conflict with the go template's {{ and }}. Since Helm charts also use these as default values, KWOK would need to support modifying the default {{ and }}. This change is straightforward but requires modification at every occurrence.

To enable coexistence between the two, there are two options:

Integrate kustomize with Helm, as detailed here: https://helm.sh/docs/topics/advanced/#post-rendering
Integrate Helm with kustomize, as detailed here: https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/helmcharts
Option 2 (integrating Helm into kustomize) appears to be the more feasible solution.

@dmitsh, what are your thoughts on this?

### Why is this needed?

Helm charts are widely used, making it easier to configure, create, and manage virtual clusters.

**Comment by yuanchen8911** [comment]
cc @wzshiming @dmitsh  Created an issue on helm support.

**Comment by dmitsh** [comment]
Could you elaborate about the conflict with the go template?

**Comment by dmitsh** [comment]
Regardless, we are using ArgoCD to automate deployments of components with Helm. The goal is to deploy all the components without user intervention or input.

**Comment by yuanchen8911** [comment]
> Could you elaborate about the conflict with the go template?

I think what Shiming referenced to was a helm template needs additional `{{` `}}` in a stage's `statusTemplate`.

 ```
  next:
    statusTemplate: |
      {{`

     `}}

```

**Comment by wzshiming** [comment]
@dmitsh
@yuanchen8911

I've released the first helm chart to validate the CI process, and it seems to be working pretty well.

https://artifacthub.io/packages/helm/kwok/kwok
https://github.com/kubernetes-sigs/kwok/tree/main/charts/kwok
