### ISSUE TITLE
[kwokctl] Support for exposing component ports to hosts in container executing

### ISSUE THREAD

**Issue by wzshiming** [kubernetes-sigs/kwok#1036]
### What would you like to be added?

```
kwokctl port-forward NAME LOCAL_PORT
```

- binary
  - TCP forward
- container (docker, podman, nerdctl)
  - TCP Forward go through `docker exec -i <kwok-controller-name> nc <target> <port>`
- kind
  - Convert `kwokctl port-forward ...` to `kubectl port-forward ...`

### Why is this needed?

In most cases, the ports are not actively exposed when the cluster is created, and trying to access a component's port in the middle of the process can be difficult, so we wanted a way to support it.

**Comment by NeerajNagure** [comment]
Hi @wzshiming I would like to work on this issue. Can you please provide more details on the issue as in how can we add the support?

**Comment by VasuDevrani** [comment]
can i try this?
