### ISSUE TITLE
[UMBRELLA] Code Cleanup

### ISSUE THREAD

**Issue by wzshiming** [kubernetes-sigs/kwok#107]
``` bash
cat .golangci.yaml | grep '# - ' | awk '{print $3}'
```

https://golangci-lint.run/usage/linters

- [x] errcheck #118
- [x] errorlint #109
- [x] gocritic #112
- [x] gocyclo #173
- [x] gosec #172
- [x] gosimple #111
- [x] importas #111
- [x] nilerr #110
- [x] prealloc #110
- [x] revive #234
- [ ] rowserrcheck [ignore]
- [x] staticcheck #145
- [x] stylecheck #136
- [x] typecheck #108
- [x] usestdlibvars #114
- [x] whitespace #108

### Install golangci-lint

```
go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.50.1
```

### Uncomment/Add on the checks you want to cleanup

https://github.com/kubernetes-sigs/kwok/blob/main/.golangci.yaml#L3

### Check

Run `golangci-lint run -c .golangci.yaml` based on root of this repo

### Clean up

Clean up the code based on the error reported by the check

## Example

#108

**Comment by Zhuzhenghao** [comment]
I will clean up : 
 rowserrcheck
 staticcheck
 stylecheck

**Comment by carlory** [comment]
I will clean up :

staticcheck
stylecheck

**Comment by Songjoy** [comment]
I will clean up :
errcheck
revive
rowserrcheck

**Comment by kinzhi** [comment]
I will clean up :
 gocyclo
 gosec

**Comment by kinzhi** [comment]
I will clean up :

- gocyclo
- gosec

**Comment by my-git9** [comment]
I will clean up :
 - revive
-  gocritic

**Comment by wlp1153468871** [comment]
I will clean up :

staticcheck
stylecheck

**Comment by Songjoy** [comment]
@wzshiming can you give me some guide ?

```
➜  kwok git:(rowserrcheck) ✗ go version
go version go1.19.2 darwin/arm64

➜  kwok git:(rowserrcheck) ✗ golangci-lint run -c .golangci.yaml
WARN [linters_context] rowserrcheck is disabled because of generics. You can track the evolution of the generics support by following the https://github.com/golangci/golangci-lint/issues/2649.
```

**Comment by wzshiming** [comment]
> @wzshiming can you give me some guide ?
> 
> ```
> ➜  kwok git:(rowserrcheck) ✗ go version
> go version go1.19.2 darwin/arm64
> 
> ➜  kwok git:(rowserrcheck) ✗ golangci-lint run -c .golangci.yaml
> WARN [linters_context] rowserrcheck is disabled because of generics. You can track the evolution of the generics support by following the https://github.com/golangci/golangci-lint/issues/2649.
> ```

So let's skip `rowserrcheck` and wait for his subsequent updates

**Comment by ShivamTyagi12345** [comment]
working on gocyclo

**Comment by qingwave** [comment]
/assign
work on `gocyclo`

- [ ] pkg/kwokctl/runtime/binary/cluster.go:127:1: cyclomatic complexity 46 of func `(*Cluster).Up` is high
- [ ] pkg/config/vars.go:109:1: cyclomatic complexity 49 of func `setKwokctlConfigurationDefaults` is high

**Comment by wzshiming** [comment]
All completed except for rowserrcheck
/close
