### ISSUE TITLE
Enhancement: Update Prometheus Data Source Docs for Grafana

### ISSUE THREAD

**Issue by network-charles** [kubernetes-sigs/kwok#1078]
This isn't necessarily a bug, but an enhancement to [this](https://kwok.sigs.k8s.io/docs/examples/prometheus/) existing documentation.

> Add the Prometheus data source, `http://host.docker.internal:9090`, on Grafana

While setting up Prometheus, using the above URL to access the host port didn't work on my Ubuntu machine running on AWS, I had this error `Error reading Prometheus: Post "http://host.docker.internal:9090/api/v1/query": dial tcp: lookup host.docker.internal on 172.31.0.2:53: no such host`.

According to this [Stackoverflow](https://stackoverflow.com/questions/48546124/what-is-the-linux-equivalent-of-host-docker-internal) answer, the URL doesn't work by default, you'd have to use this flag `--add-host=host.docker.internal:host-gateway` when creating the container.

I opted to use my host's IP address. In my case, this was the public IP address of my host.

My suggestion is to specify that users either use `http://host.docker.internal:9090` or `http://hostIP:9090`

The documentation then becomes the below:
> Add the Prometheus data source, `http://host.docker.internal:9090` or `http://hostIP:9090`, on Grafana, replacing `hostIP` with the IP address of your host.

I'll be happy to work on this issue if it's approved.

**Comment by wzshiming** [comment]
If you'd like to enhance this that would be great, I've only tested this with docker on my macbook laptop in the early days of the project. It's a bit outdated now.
