### ISSUE TITLE
[kwokctl] Support force delete cluster

### ISSUE THREAD

**Issue by wzshiming** [kubernetes-sigs/kwok#1124]
### What would you like to be added?

Add flag `--force` to `kwokctl delete cluster`

The behavior of the command, depending on the availability of the runtime and the state of the `--force` flag, is as follows:

- If the runtime is not available:
  - When `--force` is set to `false` (default state), the cluster will not be deleted.
  - When `--force` is set to `true`, the cluster will be deleted despite the unavailability of the runtime. 

### Why is this needed?

Currently, force delete is the default

**Comment by Manoramsharma** [comment]
Hi @joeyyy09 I have already done the similar issue #1123 PR for which is already open. I was working on this one and will be going to raise a PR for this one too. Its better if we can collaborate for the same.

**Comment by joeyyy09** [comment]
Hey, @Manoramsharma. Thought this issue was open and already wrote all the code to add this flag. I'll open a PR, can you check if my implementation is correct, and any help is highly appreciated!

**Comment by Manoramsharma** [comment]
Actually adding `--all` flag to `kwokctl delete cluster` and `--force` flag includes changes to the same file that is `pkg/kwokctl/cmd/delete/cluster/cluster.go` so I thought to merge both of my changes to the single PR that is already open (see #1125)

**Comment by joeyyy09** [comment]
> Actually adding `--all` flag to `kwokctl delete cluster` and `--force` flag includes changes to the same file that is `pkg/kwokctl/cmd/delete/cluster/cluster.go` so I thought to merge both of my changes to the single PR that is already open (see #1125)

Oh yeah, just noticed. Anything works with me. I was actually seeing this as the v0.7 upgrade, once discuss with @wzshiming if he wants to add this feature in the v0.6 itself.  I've currently removed my PR issue link, if you need you can add that to your PR and fix both of them at once if he's fine. You can also go through my PR in the meantime and let me know if you've got any suggestions! Cheers!

**Comment by joeyyy09** [comment]
From the next time, maybe let's try to assign the issue before working on them so that there'll be no such confusions in the future.
