### ISSUE TITLE
Add kubeConfig.QPS option for kwok controller

### ISSUE THREAD

**Issue by jokerwyt** [kubernetes-sigs/kwok#1135]
### What would you like to be added?

An option just like `--kube-api-qps=50` should be added in [KwokConfigurationOptions](https://kwok.sigs.k8s.io/docs/generated/apis/#config.kwok.x-k8s.io/v1alpha1.KwokConfigurationOptions) (or somewhere else? idk) to configure the QPS for kwok controller. 

I noticed there is an `--disable-qps-limits` option for `kwokctl` but I think it just configures the controller manager,  rather than the kwok controller itself. 

### Why is this needed?

For mocking the cluster under a huge burst pod creating and deleting.

**Comment by wzshiming** [comment]
The kwok doesn't have a QPS limit, I thought you might need this #1122 to make a huge burst pod creating and deleting.

**Comment by jokerwyt** [comment]
> The kwok doesn't have a QPS limit, I thought you might need this #1122 to make a huge burst pod creating and deleting.

But when I wrote my custom controller using `kubebuilder`, I usually needed to set a large `kubeConfig.QPS` before I connect my controller to the API server, just like:
```

import	ctrl "sigs.k8s.io/controller-runtime"

...

	kubeConfig := ctrl.GetConfigOrDie()
	kubeConfig.QPS = 10000
	kubeConfig.Burst = 10000
	ctrl.NewControllerManagedBy(mgr).For(&corev1.Pod{}).Complete(&UnscheduledPodReconciler{
		Client:      mgr.GetClient(),
	})
```
If I don't do that I cannot send too many messages to the API server. So shouldn't we add an option for the Kwok controller too.

**Comment by wzshiming** [comment]
https://github.com/kubernetes-sigs/kwok/blob/4f5fb135109ce234d8ccdb185ed041647bc4dd90/pkg/utils/client/clientset.go#L101

In this repo, use fake flow control to make it unlimited.

**Comment by jokerwyt** [comment]
> https://github.com/kubernetes-sigs/kwok/blob/4f5fb135109ce234d8ccdb185ed041647bc4dd90/pkg/utils/client/clientset.go#L101
> 
> In this repo, use fake flow control to make it unlimited.

Oh, that helps. Thank you.
