### ISSUE TITLE
Support run xline as a etcd

### ISSUE THREAD

**Issue by liangyuanpeng** [kubernetes-sigs/kwok#1179]
### What would you like to be added?

[xline](https://github.com/xline-kv/xline) is a kv storage and wrote with rust, compatible with etcd's API, also is a CNCF project.

And this issue is request kwok can support xline as a component.

/assign 
~~/cc @ming~~

### Why is this needed?

It is convenient for people to try running xline with kwok, also can add a adopters for kwok.

**Comment by wzshiming** [comment]
I plan to define a component configuration for kwokctl, and should be able to replace any of them. this will be added to the list of things to consider.

#847

**Comment by liangyuanpeng** [comment]
Awesome! seems like it will also working for components such as prometheus and jaeger.

**Comment by wzshiming** [comment]
Yes, the expectation is general enough.
