### ISSUE TITLE
[kwokctl] Set up metrics-usage.yaml as default

### ISSUE THREAD

**Issue by wzshiming** [kubernetes-sigs/kwok#1182]
### What would you like to be added?

Set up `metrics-usage.yaml` as default when have `--enable-metrics-server` and do not have CRD/configuration like Metric, ResourceUsage and ClusterResourceUsage

### Why is this needed?

Ease of use

**Comment by logica0419** [comment]
I wanna work on this issue, but I don't know the current situation.
Could you tell me the a little more specific idea you want to implement?

**Comment by wzshiming** [comment]
https://github.com/kubernetes-sigs/kwok/blob/dbf1cca84673a5597f97ea399d10c540f6c00398/pkg/kwok/cmd/root.go#L482-L488

Here's an example of Stage's default settings.

Do similar processing logic for `--enable-metrics-server` with https://github.com/kubernetes-sigs/kwok/tree/5c13cee337d1c1f19932899029553be3ec922516/kustomize/metrics
