### ISSUE TITLE
Overflow in quantity calculations for large values in CEL expressions

### ISSUE THREAD

**Issue by MondayCha** [kubernetes-sigs/kwok#1261]
### How to use it?

- [X] kwok
- [ ] kwokctl --runtime=docker (default runtime)
- [ ] kwokctl --runtime=binary
- [ ] kwokctl --runtime=nerdctl
- [ ] kwokctl --runtime=kind

### What happened?

This issue expands on a previously submitted issue #1259 regarding incorrect Quantity calculations in CEL expressions. 

While that issue was resolved, I encountered an additional limitation when handling large Quantity values, such as `20Gi`, which results in an overflow.

### What did you expect to happen?

When carrying out operations on Quantity using CEL expressions, there should be no overflow in the result.

### How can we reproduce it (as minimally and precisely as possible)?

To reproduce the overflow issue, configure the `ClusterResourceUsage` as follows:

```yaml
apiVersion: kwok.x-k8s.io/v1alpha1
kind: ClusterResourceUsage
metadata:
  name: large-quantity-test
spec:
  usages:
  - usage:
      memory:
        expression: |
          Quantity("20Gi") * 1.0
```

The expected result should handle 20Gi precisely. Nevertheless, during this procedure, the newQuantityFromFloat64 function in [quantity.go](https://github.com/kubernetes-sigs/kwok/blob/v0.6.1/pkg/utils/cel/quantity.go#L69) will carry out the following computation:

```go
func newQuantityFromFloat64(v float64) Quantity {
    r := resource.NewScaledQuantity(int64(v * 1e9), resource.Nano)
    return NewQuantity(r)
}
```

Here, `20Gi * 1e9` results in $21,474.836,480 * 1,000,000,000 = 21,474,836,480,000,000,000$, which exceeds the maximum value for int64 ($9,223,372,036,854,775,807$). This causes an overflow error, rendering the calculated quantity inaccurate.

```shell
$ kubectl top pod
NAME                        CPU(cores)   MEMORY(bytes)   
fake-pod-5c449fc8f7-2rt7z   1m       -8796Mi
```

### Anything else we need to know?

Compared to issue #1259, this problem presents greater complexity. In the [`k8s.io/apimachinery` library](https://pkg.go.dev/k8s.io/apimachinery@v0.31.0/pkg/api/resource#Quantity.Mul), `Quantity` only supports multiplication by `int64` types:

```go
// Mul multiplies the provided y to the current value.
// It will return false if the result is inexact. Otherwise, it will return true.
func (q *Quantity) Mul(y int64) bool {
    q.s = ""
    if q.d.Dec == nil && q.i.Mul(y) {
        return true
    }
    return q.ToDec().d.Dec.Mul(q.d.Dec, inf.NewDec(y, inf.Scale(0))).UnscaledBig().IsInt64()
}
```

In the context of Kwok, users may want to dynamically calculate current resource usage based on a Pod's resource Requests or Limits. Examples include:

1. Periodically adjusting usage within a set range (e.g., from half the limits up to the full limits).
2. Performing random calculations based on the specified limits.

One workaround to avoid overflow in the `newQuantityFromFloat64` function is allowing users to directly specify the float64 Nano value in Annotations, thus bypassing `Quantity` altogether. However, this requires users to handle the calculations manually, adding to their mental load.

Another potential approach would be to trade some precision in cases of overflow, ensuring the result stays within the `int64` range.

After further discussion, I am very willing to participate in the implementation of the solution. Looking forward to collaborating on this improvement. 😊

### Kwok version

<details>

```console
$ kwok --version
0.6.1
```

</details>

### OS version

<details>

```console
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
$ uname -a
Linux act-1 6.8.0-47-generic #47~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Oct  2 16:16:55 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```
</details>

**Comment by wzshiming** [comment]
I think a megabyte of precision is enough for this data; it should be the smallest unit for the metrics server.

**Comment by wzshiming** [comment]
Ohh, I catch the root cause, it is taking the smallest unit too small...


This will increase the accuracy by 1e9

``` diff
diff --git a/pkg/utils/cel/quantity.go b/pkg/utils/cel/quantity.go
index 9b7f82ec..fe87ea33 100644
--- a/pkg/utils/cel/quantity.go
+++ b/pkg/utils/cel/quantity.go
@@ -47,7 +47,7 @@ type Quantity struct {
 // NewQuantity creates a new Quantity
 func NewQuantity(q *resource.Quantity) Quantity {
        if q == nil {
-               q = resource.NewScaledQuantity(0, resource.Nano)
+               q = resource.NewScaledQuantity(0, 0)
        }
        return Quantity{Quantity: q}
 }
@@ -62,17 +62,17 @@ func NewQuantityFromString(s string) (Quantity, error) {
 }
 
 func newQuantityFromNanoInt64(v int64) Quantity {
-       r := resource.NewScaledQuantity(v, resource.Nano)
+       r := resource.NewScaledQuantity(v, 0)
        return NewQuantity(r)
 }
 
 func newQuantityFromFloat64(v float64) Quantity {
-       r := resource.NewScaledQuantity(int64(v*10e9), resource.Nano)
+       r := resource.NewScaledQuantity(int64(v), 0)
        return NewQuantity(r)
 }
 
 func (q Quantity) nano() int64 {
-       return q.Quantity.ScaledValue(resource.Nano)
+       return q.Quantity.ScaledValue(0)
 }
 
 func (q Quantity) float() float64 {

```

**Comment by MondayCha** [comment]
@wzshiming So we just need to modify the minimum unit? What were the main considerations for using nano as the unit previously?

**Comment by wzshiming** [comment]
It works, I didn't notice the unit was too small. I only worked on this, with no other reviewer.

**Comment by wzshiming** [comment]
If possible, you could help verify that it works and add full unit test coverage. 😄

**Comment by MondayCha** [comment]
I'd be happy to participate in this. 

Should we still consider merging the previous PR #1260 , or should we wait until this new version is completed?

**Comment by wzshiming** [comment]
It can better be fixed in a PR and I will cherry-pick it to old release if necessary.

**Comment by MondayCha** [comment]
> If possible, you could help verify that it works and add full unit test coverage. 😄

@wzshiming Hello! I've updated the code #1260 and added some basic unit tests. However, since the test files and CEL function definition files are in different packages, I'm not quite sure about the specific unit test coverage. Do you have any suggestions?
