### ISSUE TITLE
[kwokctl] Add stop/start commands

### ISSUE THREAD

**Issue by ikaven1024** [kubernetes-sigs/kwok#134]
### What would you like to be added?

Add `stop` command for cluster.

### Why is this needed?

Mostly, I just want to stop the running of cluster when I don't need it, NOT deleting.

**Comment by Fish-pro** [comment]
@wzshiming 
I have a question, stop mean clean all containers or stop containers? The difference between the two is that if you are cleaning the container, the data created after startup will not exist.
Which is it?

**Comment by wzshiming** [comment]
@ikaven1024 @Fish-pro

I feel this requirements like a combination of two commands

## `kwokctl stop cluster`

``` bash
kwokctl snapshot save --path db.bak
kwokctl delete cluster
```

## `kwokctl start cluster`

``` bash
kwokctl create cluster
kwokctl snapshot restore --path db.bak
```

**Comment by ikaven1024** [comment]
Cann't we just stop containers, keep the data volume? Just like minikube
```
~ minikube stop cluster -h
Stops a local Kubernetes cluster. This command stops the underlying VM or container, but keeps user
data intact. The cluster can be started again with the "start" command.
```
