### ISSUE TITLE
[kwok] Simulate the services provided by Kubelet

### ISSUE THREAD

**Issue by wzshiming** [kubernetes-sigs/kwok#162]
### What would you like to be added?

Simulate the services provided by Kubelet for `logs`, `exec`, `attach`, `port-forward`.

- [x] #198 #238
- [x] #236 #430 #446
- [x] #216 #233
- [x] #217 #417
- [x] #237

### Why is this needed?

#159

**Comment by nikola-jokic** [comment]
Hey @wzshiming, I would really like to contribute. Can I take one of them and which one would you suggest if you agree :relaxed: ?

**Comment by wzshiming** [comment]
> Hey @wzshiming, I would really like to contribute. Can I take one of them and which one would you suggest if you agree ☺️ ?

Of course, you can choose whatever you want, currently only `port-forward` I have a clearer idea, you can try it first.

If you encounter any difficulties in the implementation or have any problems with the API definition, please feel free to discuss with me.

Thank you for taking on this work.

**Comment by nikola-jokic** [comment]
It is my pleasure! I'd love to start contributing to this amazing project! Thank you for including me. I'll start right away
