### ISSUE TITLE
Logger format enhancement

### ISSUE THREAD

**Issue by qingwave** [kubernetes-sigs/kwok#169]
### What would you like to be added?

In the kwok, print log just like follows:
```
WARN Text logger                                                               cluster=kwok key1=val1 key2=key3
```
There is a long space between msg and tags, it's not very clear from my side.

The code in logger shows:
https://github.com/kubernetes-sigs/kwok/blob/75e6b354bf5f9e81a6b178458f3c618fdad76612/pkg/log/logger_ctl.go#L129

Why we print the log length must equal the termail width?

### Why is this needed?

Print more clear log.

**Comment by wzshiming** [comment]
This is a change after v0.0.1 that has not been released yet, the expectation is to make the log output more consistent with the default runtime docker style, and in line with the structured logging style, do you have any good ideas to discuss?

``` console
$ kwokctl create cluster
Creating cluster                                                        cluster=kwok
Starting cluster                                                        cluster=kwok
[+] Running 6/6
 ⠿ Network kwok-kwok                            Created                        0.0s
 ⠿ Container kwok-kwok-etcd                     Started                        0.3s
 ⠿ Container kwok-kwok-kube-apiserver           Started                        0.5s
 ⠿ Container kwok-kwok-kwok-controller          Started                        0.9s
 ⠿ Container kwok-kwok-kube-controller-manager  Started                        0.9s
 ⠿ Container kwok-kwok-kube-scheduler           Started                        0.9s
Cluster is created                                                      cluster=kwok
You can now use your cluster with:

    kubectl config use-context kwok-kwok

Thanks for using kwok!


```

**Comment by qingwave** [comment]
We can split message and attrs with just a comma, looks like
```
# with comma
Creating cluster, cluster=kwok

# or brackets
Creating cluster(cluster=kwok,somekey=someval)
```

I think it's more explicit than now
```
Creating cluster                                                        cluster=kwok
```

**Comment by wzshiming** [comment]
In fact, the beginning is similar to this, but too much output piled up together is a bit confusing, in fact, only the left side is the main message, the right side is only the left side of the additional information, I am referring to the style of a logger library I have used before, I feel that it is quite good as the format of the cli tool.

https://github.com/sirupsen/logrus

**Comment by qingwave** [comment]
Thanks for your explaination
