### ISSUE TITLE
Cannot compile in bash 3.2.x

### ISSUE THREAD

**Issue by chaunceyjiang** [kubernetes-sigs/kwok#177]
### How to use it?

- [ ] kwok
- [ ] kwokctl --runtime=docker (default runtime)
- [ ] kwokctl --runtime=binary
- [ ] kwokctl --runtime=nerdctl
- [ ] kwokctl --runtime=kind

### What happened?

![image](https://user-images.githubusercontent.com/17962021/209619754-5f567a5f-ccd9-44f1-80fc-88adb7bf2122.png)

### What did you expect to happen?

Can compile.

### How can we reproduce it (as minimally and precisely as possible)?

1. Mac m1
2. GNU bash, version 3.2.57(1)-release-(arm64-apple-darwin22) 
3. make build

### Anything else we need to know?

https://github.com/kubernetes-sigs/kwok/blob/483e9d7e71acd8ec4ab38d12510b7bc55153b18c/hack/get-platform.sh#L45

Only bash version 4.0 or above is supported.

### OS version

<details>
```console        
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Darwin:
$ uname -a
Darwin chauncey-2.local 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:30 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T8103 arm64

GNU bash, version 3.2.57(1)-release-(arm64-apple-darwin22)

# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

**Comment by wzshiming** [comment]
bash 4 was released 14 years ago, we should upgrade.

**Comment by chaunceyjiang** [comment]
> bash 4 was released 14 years ago, we should upgrade.

I don't think we should rely on the bash version.

https://github.com/kubernetes-sigs/kwok/blob/f2419ade111d31ffb615b9e5692720088305390a/Makefile#L57

```
PLATFORM ?= $(GOOS)/$(GOARCH)
```
i think this will fix the issue.

**Comment by wzshiming** [comment]
Yes, we modify it to `$(GOOS)/$(GOARCH)` and delete `./hack/get-platform.sh`
