### ISSUE TITLE
[kwok] Evaluate the other promising contextual logger

### ISSUE THREAD

**Issue by wzshiming** [kubernetes-sigs/kwok#2]
let's create an issue to evaluate the other promising contextual logger.

Kwok should probably output a structured log, Maybe use that implements the https://github.com/go-logr/logr or https://golang.org/x/exp/slog
Kwokctl should probably output a friendly log

_Originally posted by @Huang-Wei in https://github.com/kubernetes-sigs/kwok/pull/1#discussion_r935138322_

**Comment by d3vus** [comment]
Hi @wzshiming, can i know the status of this issue - is it open or merged?

**Comment by wzshiming** [comment]
It's still open
