### ISSUE TITLE
support customized KubeSchedulerConfiguration

### ISSUE THREAD

**Issue by pacoxu** [kubernetes-sigs/kwok#200]
### What would you like to be added?

inspired by a user in tw.

> I tried kwok and it feels pretty good. But I still can't seem to set the KubeSchedulerConfiguration.

### Why is this needed?

we use it to simulate scheduling of our real cluster and want to make the configuration the same as our real cluster

**Comment by wzshiming** [comment]
https://kubernetes.io/docs/reference/scheduling/config/
