### ISSUE TITLE
[kwokctl] Update start/stop for nerdctl

### ISSUE THREAD

**Issue by wzshiming** [kubernetes-sigs/kwok#245]
### What would you like to be added?

nerdctl 1.2 or later, change it to look like docker. Keep the rest unchanged.

### Why is this needed?

https://github.com/kubernetes-sigs/kwok/blob/8c30ec90a88d85fd04579fddb00a491b87ef96e0/pkg/kwokctl/runtime/compose/cluster.go#L550-L555

https://github.com/kubernetes-sigs/kwok/blob/8c30ec90a88d85fd04579fddb00a491b87ef96e0/pkg/kwokctl/runtime/compose/cluster.go#L570-L586

https://github.com/kubernetes-sigs/kwok/blob/8c30ec90a88d85fd04579fddb00a491b87ef96e0/pkg/kwokctl/runtime/compose/cluster.go#L598-L606

**Comment by wzshiming** [comment]
/reopen

Revert by #260

**Comment by utkarsh-singh1** [comment]
Hi @wzshiming, is this issue still in work?

**Comment by utkarsh-singh1** [comment]
The PR seems to be reverted due to issue with `nerdctl stop` .

**Comment by wzshiming** [comment]
Thanks for your attention, this issue has been fixed I forgot to update it, refactoring the way containers are started, and no longer relying on compose.

Fixed by #607
