### ISSUE TITLE
Add e2e for nerdctl on darwin

### ISSUE THREAD

**Issue by wzshiming** [kubernetes-sigs/kwok#246]
### What would you like to be added?

https://github.com/containerd/nerdctl#macos

### Why is this needed?

NONE

**Comment by wzshiming** [comment]
@Zhuzhenghao
It seems that nerdctl is not very mature on the Mac and has a lot of problems, so let's postpone this issue.

**Comment by wzshiming** [comment]
@zwpaper
I removed nerdctl from the v0.2 as a second runtime for kwokctl on the Mac to prevent anyone from using it unknowingly.

**Comment by zwpaper** [comment]
Ok, I was working on it and spent pretty much time on the CI for nerdctl on mac.

But I did found some random errors on CI, but can not reproduce it locally... really weird, did not figure out why yet...

**Comment by Zhuzhenghao** [comment]
Okay.
