### ISSUE TITLE
Slow bootup (5s)

### ISSUE THREAD

**Issue by Pithikos** [kubernetes-sigs/kwok#335]
### How to use it?

- [ ] kwok
- [ ] kwokctl --runtime=docker (default runtime)
- [ ] kwokctl --runtime=binary
- [ ] kwokctl --runtime=nerdctl
- [ ] kwokctl --runtime=kind

### What happened?

Based on [this blog article](https://www.kubernetes.dev/blog/2023/03/01/introducing-kwok/) I was told to report the startup time.

Essentially I use kwok for testing and TDD. It is faster than Minikube and that's why I stuck with it. Still however it's nowhere near "near instant" as advertised in that blog post. It takes at best 5s just to bootstrap when running my test-suite (way better than 20-60s for Minikube) but still quite slow for rapid TDD.

benchmark.sh
```
#! /bin/bash

# Start daemon
container_id=$(docker run --rm -d -p 8080:8080 registry.k8s.io/kwok/cluster:v1.26.0)

# Count time taken to bootstrap
start=$(date +%s.%N)
while true; do
    kubectl -s :8080 get service
    if [ $? -eq 0 ]; then
        break
    fi
    sleep 0.1
done
end=$(date +%s.%N)
runtime=$(python -c "print(round($end - $start, 2))")
echo "Time taken to bootstrap: ${runtime}s"

# Kill daemon
docker stop $container_id
```

This gives about 5 seconds. Is this the expected time?

### What did you expect to happen?

<1-2s to be near instant

### How can we reproduce it (as minimally and precisely as possible)?

Run the script on a modern machine with i7 CPU.

### Kwok version

<details>

```console
$ kwok --version
kwok: command not found

$ kwokctl --version
kwokctl: command not found
```

</details>

### OS version

<details>
```console

# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

$ uname -a
Linux firefly 5.4.0-137-generic #154-Ubuntu SMP Thu Jan 5 17:03:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```
</details>

**Comment by wzshiming** [comment]
I've tried it and it's only slow in the all-in-one image, I've found the cause and will optimise the bootup speed in future.

**Comment by wzshiming** [comment]
Currently, kwokctl does preparation and version checking when creating a cluster, which causes a speed drop. After trying to hardcode off the various checks, I did manage to get just etcd and apiserver to start in less than 2 seconds.
If you are so sensitive to speed, perhaps we could add a flag to make apiserver available immediately after startup without having to wait for readiness, but this could lead to erratic behaviour.

**Comment by wzshiming** [comment]
#359 This is a change that skips all checks, just as fast as the original version without any checks, although fast but many things are not really ready, mainly waiting for components like Apiserver to be ready. 

I tried it with your script.

| | v0.1.0 | #359 |
| - | - | - |
|my mac m1| 4s | 1.6s |
|my old mac| 10s | 4s |

If you are interested you can try to build it based on that PR `make build-cluster-image`

**Comment by Pithikos** [comment]
Just thought uI'll share that for testing I've managed to speed things up by instead of re-creating the kwok cluster for each test, to simply re-use the same and then clear it for each test. Should work for most use-cases.

pytest pseudocode
```
@pytest.fixture(autouse=True, scope="function")
def kwok_cluster_reset(kwok_cluster):
    """ Reset cluster on each test """
    yield
    kwok_cluster.run("delete all --all --now --ignore-not-found")


@pytest.fixture(scope="session")
def kwok_cluster():
    # start cluster with initial nodes
    ....
    
    yield Kube()
```

**Comment by wzshiming** [comment]
Cool, if there is more data in the cluster, re-creating may be faster than emptying. However, emptying is indeed a very effective method in simple scenarios

**Comment by wzshiming** [comment]
I tried the image based on kwok 0.3.0 and the boot time is already down to 2s on my laptop

registry.k8s.io/kwok/cluster:v0.3.0-k8s.v1.27.3

https://kwok.sigs.k8s.io/docs/user/all-in-one-image/

**Comment by wzshiming** [comment]
v0.3 startup speed is now under 2 seconds, feel free to open it if you have any other questions

/close
