### ISSUE TITLE
Support comments and/or empty documents at top of config files

### ISSUE THREAD

**Issue by hiddeco** [kubernetes-sigs/kwok#343]
### How to use it?

- [ ] kwok
- [ ] kwokctl --runtime=docker (default runtime)
- [ ] kwokctl --runtime=binary
- [ ] kwokctl --runtime=nerdctl
- [ ] kwokctl --runtime=kind

### What happened?

Attempted to create a cluster with `kwokctl --name kwok --config ./config.yaml create cluster`, with the following head:

```
# Ref: <some URL>
---
kind: Stage
apiVersion: kwok.x-k8s.io/v1alpha1
...further document
```

which yielded:

```console
ERROR Unsupported config path=["./config.yaml"] err="unexpected end of JSON input"
```

After removing the comment and document divider, it worked as expected.

### What did you expect to happen?

I expected it to ignore the empty first document, as the [API machinery YAML stream reader](https://pkg.go.dev/k8s.io/apimachinery/pkg/util/yaml) does.

### How can we reproduce it (as minimally and precisely as possible)?

See "what happened".

### Kwok version

<details>

```console
$ kwokctl --version
kwokctl version v0.1.0
```

</details>

**Comment by wzshiming** [comment]
Thank you, reproduced successfully. 🎉

/triage accepted

**Comment by wzshiming** [comment]
Would you like to try to fix it? 😉

https://github.com/kubernetes-sigs/kwok/blob/b7fd256c5e11abf7bb385c7069884ae751cba607/pkg/config/config.go#L304
