### ISSUE TITLE
kwok cni setup() and remove() parameter

### ISSUE THREAD

**Issue by charles-chenzz** [kubernetes-sigs/kwok#370]
do we actually need the parameter input into the function?
![image](https://user-images.githubusercontent.com/73322208/223897318-4a6bfeb8-35f3-4446-9472-a8da56af6dc3.png)

I check the pod_controller.go files and only line 513 and line 490 call it and it will return hard-code error, so can I assume that the parameter is no needed?

**Comment by wzshiming** [comment]
This file is stub for https://github.com/kubernetes-sigs/kwok/blob/main/pkg/kwok/cni/cni_linux.go

**Comment by charles-chenzz** [comment]
it's like dependency inject into cni_linux.go files?

**Comment by wzshiming** [comment]
No, it is a choice of different source files depending on the platform.

**Comment by charles-chenzz** [comment]
can I say if on non-linux plat the function parameter is useless but in linux plat it needs the parameter so we need to keep the parameter same?

**Comment by wzshiming** [comment]
Yeah, you can say it that way.

**Comment by charles-chenzz** [comment]
thanks, I think no more question on this issue now so I closed it
