### ISSUE TITLE
Support CRD validation

### ISSUE THREAD

**Issue by rkr-kununu** [kubernetes-sigs/kwok#373]
### What would you like to be added?

I would like the ability to add applications to a kwok's cluster which have their own CRDs (ie: Traefik's IngressRoute for example) and have kwok verify my usage of these CRDs is syntactically valid (ie: I've created an IngressRoute). 

### Why is this needed?

I'm exploring a "low-effort", automated, gitops approaches for testing/upgrading infrastructure changes.  For example, creating a PR with a revision increase to Traefik... then (in our CICD pipeline) using kwok to create a "mock" of our infrastructure (with the new Traefik version) and try to apply our application (which uses the CRDs).  If kwok validates that our application is compatible with the (untested) version of Traefik, then the next step in the pipeline would be to create an infrastructure to test the functionality (out of scope for this ticket ;).

Of course there are tools which can verify that our usage of our CRDs is valid.  However, many require a running kubernetes cluster (with the new CRDs installed).  There are also some validators which support "offline" validation, but these often require creating, maintaining, or downloading configuration files (OpenAPI definitions) which may or may not exist (or need to be manually created/maintained).

The elegance of kwok is that it's lightweight and it would just follow the same process as constructing a "real" infrastructure.

**Comment by wzshiming** [comment]
It sounds like starting the CRD validator externally, using kubeconfig to work for the cluster would accomplish this, am I misunderstanding?
