### ISSUE TITLE
Cannot install kwok in cluster

### ISSUE THREAD

**Issue by yangcheng-icbc** [kubernetes-sigs/kwok#398]
### How to use it?

- [X] kwok
- [ ] kwokctl --runtime=docker (default runtime)
- [ ] kwokctl --runtime=binary
- [ ] kwokctl --runtime=nerdctl
- [ ] kwokctl --runtime=kind

### What happened?

[root@VM-4-9-centos tmp.32Q0AifEUN]# ls
kustomization.yaml  kwok.yaml
[root@VM-4-9-centos tmp.32Q0AifEUN]# kubectl kustomize "${KWOK_WORK_DIR}" > "${KWOK_WORK_DIR}/kwok.yaml"
Error: rawResources failed to read Resources: Load from path https://github.com/kubernetes-sigs/kwok/kustomize/kwok?ref=v0.1.1 failed: evalsymlink failure on '/tmp/tmp.32Q0AifEUN/https:/github.com/kubernetes-sigs/kwok/kustomize/kwok?ref=v0.1.1' : lstat /tmp/tmp.32Q0AifEUN/https:: no such file or directory

### What did you expect to happen?

I got a error when use "kubectl  kustomize"

### How can we reproduce it (as minimally and precisely as possible)?

Render kustomization yaml 

### Anything else we need to know?

kubernetes version=1.17.5

### Kwok version

<details>

```console
$ kwok --version
v0.1.1
# paste output here

$ kwokctl --version
v0.1.1
# paste output here
```

</details>

### OS version

<details>
```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Darwin:
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

**Comment by wzshiming** [comment]
Duplicative of #270

**Comment by wzshiming** [comment]
Duplicative of https://github.com/kubernetes-sigs/kwok/issues/270
/close
