### ISSUE TITLE
☂️ Code Cleanup for shell

### ISSUE THREAD

**Issue by Zhuzhenghao** [kubernetes-sigs/kwok#470]
https://www.shellcheck.net/wiki/

## Tasks

- [X] SC2002 #492
- [x] SC2009 #498
- [x] SC2015 #521
- [X] SC2034 #491
- [x] SC2038 #500
- [x] SC2046  #554
- [x] SC2053 #496
- [x] SC2069 #504
- [x] SC2076 #546
- [x] SC2086 #519
- [x] SC2155 #501
- [x] SC2126 #497
- [x] SC2181 #560
- [x] SC2207 #561
- [X] SC2294 #493

### Install shellcheck

https://github.com/koalaman/shellcheck#installing

On macOS (OS X) with Homebrew:

```shell
brew install shellcheck
```

### Remove the rule you want to cleanup

https://github.com/kubernetes-sigs/kwok/blob/main/hack/verify-shellcheck.sh#L36

### Check

Run the following based on root of this repo:

```shell
./hack/verify-shellcheck.sh 
```

### Clean up
Clean up the code based on the error reported by the check

## Example

PR:
- #491
- #492
- #493

**Comment by Songjoy** [comment]
/assign

Pick SC2009 SC2038 SC2053 SC2126

**Comment by yulng** [comment]
/assign
Pick SC2207

**Comment by liu-xg** [comment]
/assign
Pick SC2015

**Comment by yulng** [comment]
/assign
Pick SC2046

**Comment by yulng** [comment]
https://github.com/kubernetes-sigs/kwok/pull/533

**Comment by Michael-Xing** [comment]
/assign
Pick SC2076

**Comment by Michael-Xing** [comment]
/assign

Pick SC2181

**Comment by Michael-Xing** [comment]
/assign
Pick SC2181

**Comment by Michael-Xing** [comment]
/assign
Pick SC2181

**Comment by Michael-Xing** [comment]
/assign
Pick SC2181

**Comment by yulng** [comment]
https://github.com/kubernetes-sigs/kwok/pull/561
