### ISSUE TITLE
Reduce test time "test-kwokctl (macos-latest, kind)"

### ISSUE THREAD

**Issue by wzshiming** [kubernetes-sigs/kwok#536]
### Which jobs are failing?

NONE

### Which tests are failing?

This test takes too long try to reduce it

### Since when has it been failing?

NONE

**Comment by Eayne** [comment]
/assign
I think I have a solution. How can I test it on Github Action Workflow?
@wzshiming

**Comment by Eayne** [comment]
I successfully reduce test time of test-kwokctl (macos-latest, kind) from 80 minutes to 40 minutes.
<img width="738" alt="截屏2023-05-02 20 32 44" src="https://user-images.githubusercontent.com/34951982/235667466-41be7172-85e1-46c9-bdf9-db5bf58f5448.png">
<img width="665" alt="截屏2023-05-02 20 33 05" src="https://user-images.githubusercontent.com/34951982/235667525-01489ee7-e74b-452e-994c-0257e7ca03b5.png">

**Comment by wzshiming** [comment]
Since Kind-related tests are quite unstable in Github Action, they have been removed from the CI and will only be verified manually before release.

/close
