### ISSUE TITLE
Trying to install linkerd on kwok

### ISSUE THREAD

**Issue by dewijones92** [kubernetes-sigs/kwok#564]
### How to use it?

- [ ] kwok
- [X] kwokctl --runtime=docker (default runtime)
- [ ] kwokctl --runtime=binary
- [ ] kwokctl --runtime=nerdctl
- [ ] kwokctl --runtime=kind

### What happened?

Aplogies, I don't know if the issue is caused by linkerd or kwok. If anyone can point me in the right direction that would be good thanks 😊

`docker run --rm -it -p 8080:8080 registry.k8s.io/kwok/cluster:v0.2.0-k8s.v1.27.1`

when trying to install linkerd:
```
× can read extension-apiserver-authentication configmap
    --requestheader-client-ca-file is not configured
    see https://linkerd.io/2.13/checks/#pre-k8s for hints
‼ no clock skew detected
    clock skew detected for node(s): fake-node, kwok-node-1
    see https://linkerd.io/2.13/checks/#pre-k8s-clock-skew for hints
```

Apologies

### What did you expect to happen?

For linkerd to install successfully

### How can we reproduce it (as minimally and precisely as possible)?

`docker run --rm -it -p 8080:8080 registry.k8s.io/kwok/cluster:v0.2.0-k8s.v1.27.1`
then try to install linkerd in that container with these commands
https://linkerd.io/2.13/getting-started/

### Anything else we need to know?

```
root@dewiserver:/home/dewi/code/vagrant-kubeadm-kubernetes# kubectl get nodes
NAME          STATUS   ROLES   AGE    VERSION
fake-node     Ready    agent   93m    fake-new
kwok-node-0   Ready    agent   9h     fake
kwok-node-1   Ready    agent   7h7m   fake
```

### Kwok version

```
root@dewiserver:/home/dewi/code/vagrant-kubeadm-kubernetes# docker exec cool_hawking kwokctl kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.27.1
Kustomize Version: v5.0.1
Server Version: v1.27.1
```

### OS version

cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

**Comment by wzshiming** [comment]
Are you trying to test the Linkerd controller?
it looks need to enable extension-apiserver.

**Comment by dewijones92** [comment]
@wzshiming 
many thanks for your reply
but that command gives me an error https://github.com/kubernetes-sigs/kwok/issues/567

**Comment by dewijones92** [comment]
I would love a reply @wzshiming 
I really appreciate your time :)

**Comment by wzshiming** [comment]
I've tried it and it seems to be working very well

``` bash
kwokctl create cluster --runtime kind
linkerd check --pre
linkerd install --crds | kubectl apply -f -
linkerd install| kubectl apply -f -
kubectl patch deploy linkerd-destination -n linkerd --type=json -p='[{"op":"add","path":"/spec/template/spec/nodeName","value":"kwok-kwok-control-plane"}]'
kubectl patch deploy linkerd-identity -n linkerd --type=json -p='[{"op":"add","path":"/spec/template/spec/nodeName","value":"kwok-kwok-control-plane"}]'
kubectl patch deploy linkerd-proxy-injector -n linkerd --type=json -p='[{"op":"add","path":"/spec/template/spec/nodeName","value":"kwok-kwok-control-plane"}]'
linkerd check


kubectl apply -f - <<EOF
apiVersion: v1
kind: Node
metadata:
  annotations:
    node.alpha.kubernetes.io/ttl: "0"
    kwok.x-k8s.io/node: fake
  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/os: linux
    kubernetes.io/arch: amd64
    kubernetes.io/hostname: kwok-node-0
    kubernetes.io/os: linux
    kubernetes.io/role: agent
    node-role.kubernetes.io/agent: ""
    type: kwok
  name: kwok-node-0
status:
  allocatable:
    cpu: 32
    memory: 256Gi
    pods: 110
  capacity:
    cpu: 32
    memory: 256Gi
    pods: 110
EOF

curl --proto '=https' --tlsv1.2 -sSfL https://run.linkerd.io/emojivoto.yml \
  | kubectl apply -f -
kubectl get -n emojivoto deploy -o yaml \
  | linkerd inject - \
  | kubectl apply -f -
```

**Comment by wzshiming** [comment]
https://kwok.sigs.k8s.io/docs/examples/linkerd/

I've added documentation for this, feel free to open it if you still have questions
/close
