### ISSUE TITLE
[kwokctl] Download Docker-Compose-v2 automatically if necessary

### ISSUE THREAD

**Issue by wzshiming** [kubernetes-sigs/kwok#62]
https://github.com/docker/compose

**Comment by karhow** [comment]
why we need it ?

**Comment by wzshiming** [comment]
`Docker Desktop` comes with docker-compose, but the default installation on Linux using package management does not come with `docker-compose`
So we can download `docker-compose` if it is not installed on our machine

**Comment by utkarsh-singh1** [comment]
Hey @wzshiming, if no one is working on this issue, I would like to work on it.

**Comment by wzshiming** [comment]
Please do it. I'm glad you're working here.

**Comment by fengshunli** [comment]
ok,i see @wzshiming
