### ISSUE TITLE
Provide option to configure the "KwokConfiguration" for "kwok in cluster".

### ISSUE THREAD

**Issue by sharath-sysdig** [kubernetes-sigs/kwok#656]
### What would you like to be added?

We added a config map containing "https://kwok.sigs.k8s.io/docs/user/stages-configuration/" and mounted the volume on the kwok deployment file generated by Kustomization, with --config option, however this is not working. 

So would be great if this is supported.

### Why is this needed?

feature parity with kwokctl.

**Comment by wzshiming** [comment]
Of course, I have plans to support crd for this.
#264
