### ISSUE TITLE
[kwok] Allow for delay & jitter on pod-controller applying Ready condition to pod

### ISSUE THREAD

**Issue by nagygergo** [kubernetes-sigs/kwok#66]
/kind feature

For testing monitoring tools, and deployment tools like helm/gitops simulating a large amount of load it's useful to have kwok set up in a cluster. An issue with that is kwok is moving pods to Ready too fast to simulate a realistic usecase. 

Would it be ok to add some deployment time configuration to kwok that will apply some delay (with jitter) before it moves pods to Ready state?

**Comment by wzshiming** [comment]
For this issue, I've actually been looking forward to designing a generic [Pod lifecycle simulation solution](67).
Not only including delayed Ready, but also simulating some complex Pod changes.

**Comment by wzshiming** [comment]
I have a preliminary design before, and I will implement it subsequently if there is no better design. #67

**Comment by nagygergo** [comment]
Ok, let's move the discussion to #67.
