### ISSUE TITLE
enhancement for metrics

### ISSUE THREAD

**Issue by wzshiming** [kubernetes-sigs/kwok#670]
### What would you like to be added?

- [ ] /metrics
- [ ] /metrics/cadvisor
- [x] #671
- [ ] /metrics/probes
- [x] #480
- [x] Implementation [custom.metrics.k8s.io](https://github.com/kubernetes/metrics/tree/master/pkg/apis/custom_metrics) API, https://github.com/wzshiming/custom-metrics-apiserver-simulator
- [x] #747

### Why is this needed?

continue https://github.com/kubernetes-sigs/kwok/issues/199

**Comment by nikola-jokic** [comment]
Hey @wzshiming,

I'd like to help :relaxed: Which one can I take?

**Comment by wzshiming** [comment]
> Hey @wzshiming,
> 
> I'd like to help ☺️ Which one can I take?

I'm currently trying to integrate metric-server, which uses "/metrics/resource", but I don't know how the rest of it will be used yet. 


I'm going to make Metric a CRD, which requires functionality that would be great if you're interested in participating 

- dynamically add and remove http paths for metrics

- Prometheus to dynamically discover collection targets

**Comment by nikola-jokic** [comment]
Great, so just to understand where I can help

If metrics are going to be CRDs, then will they be used in `--config`, or are they going to be applied after the `kwok` starts?
If they are going to be used after the `kwok` starts, then should we create a controller which is responsible for reacting on metric CRD, updating the metric server. The metric server will handle route updates.

But also, please feel free to let me know that this is all taken care of, I don't want to slow down your progress in any way :relaxed:

**Comment by wzshiming** [comment]
Yes, your understanding is correct.

I might need to design a bit more about metric configurations, how to configure the metrics and collection paths for multiple nodes and configure the metrics for a single pod. 

If you have any ideas, please feel free to let me know

**Comment by Horiodino** [comment]
hey @wzshiming  I would like to contribute , I have used metrices server Api and also building projects.

**Comment by wzshiming** [comment]
Thank you for your interest, metric simulation is still in the early stages of exploration and needs to be coupled with use cases to enable further planning.

**Comment by Horiodino** [comment]
all right 👍
