### ISSUE TITLE
[kwokctl] Move `--kube-audit-policy` and `--kube-scheduler-config` into `--config`

### ISSUE THREAD

**Issue by wzshiming** [kubernetes-sigs/kwok#685]
### What would you like to be added?

Use the corresponding configuration according to kind in --config

### Why is this needed?

Reduce flags

**Comment by jongwooo** [comment]
Can I work on this issue?

**Comment by wzshiming** [comment]
sure, feel free to take it.

**Comment by jongwooo** [comment]
I'm having a bit of difficulty with this issue, is there anything I can refer to?

**Comment by wzshiming** [comment]
nope. I'll give you an idea.

Define an object RawContent that implements InternalObject, wrap its content in RawContent according to apiVersion and kind in Load, and pass it out to be extracted later when needed.
https://github.com/kubernetes-sigs/kwok/blob/a867072d6316b27b4d7f2c4ddd47c52121b18420/pkg/config/config.go#L250

WDYT?

**Comment by jongwooo** [comment]
@wzshiming Thank you for the kind explanation. I'll give it a try!
