### ISSUE TITLE
INTERNAL-IP not getting populated

### ISSUE THREAD

**Issue by swathinsankaran** [kubernetes-sigs/kwok#694]
### How to use it?

- [ ] kwok
- [ ] kwokctl --runtime=docker (default runtime)
- [ ] kwokctl --runtime=binary
- [ ] kwokctl --runtime=nerdctl
- [ ] kwokctl --runtime=kind

### What happened?

Followed the steps mentioned in the document https://kwok.sigs.k8s.io/docs/user/all-in-one-image/ and created a node as discussed in the document https://kwok.sigs.k8s.io/docs/user/kwok-manage-nodes-and-pods/#create-a-node.

Getting the following as node output.

```
vmware@vmware:~/.kube$ kubectl get nodes -o wide
NAME          STATUS   ROLES   AGE   VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE    KERNEL-VERSION   CONTAINER-RUNTIME
kwok-node-0   Ready    agent   12s   fake      <none>        <none>        <unknown>   kwok-v0.3.0      kwok-v0.3.0
vmware@vmware:~/.kube$
```

### What did you expect to happen?

I am expecting  `INTERNAL-IP` field to be populated with an IP.

### How can we reproduce it (as minimally and precisely as possible)?

1. Deploy the latest all-in-one-image of kwok.
2. Create a node
3. Check the internal-ip.

### Kwok version

registry.k8s.io/kwok/cluster:v0.3.0-k8s.v1.27.3

### OS version

same behavior in the latest mac and ubuntu 20.04

**Comment by wzshiming** [comment]
https://kwok.sigs.k8s.io/docs/user/kwok-manage-nodes-and-pods/#update-spec-of-nodes-or-pods

Add the following to your node yaml 

``` yaml
status:
  addresses:
  - address: 10.0.0.1
    type: InternalIP
```

**Comment by swathinsankaran** [comment]
Thanks @wzshiming for the quick response.
So I can mutate the node in whichever way that I want.
