### ISSUE TITLE
An error occurs when the Kwok controller updates the node lease.

### ISSUE THREAD

**Issue by xiqiu618** [kubernetes-sigs/kwok#705]
### How to use it?

- [X] kwok
- [X] kwokctl --runtime=docker (default runtime)
- [ ] kwokctl --runtime=binary
- [ ] kwokctl --runtime=nerdctl
- [ ] kwokctl --runtime=kind

### What happened?

An error occurs when the Kwok controller updates the node lease. It is recommended to change the update operation to  patch.

{"time":"2023-07-06T02:30:57.619496691Z","level":"ERROR","source":{"function":"sigs.k8s.io/kwok/pkg/kwok/controllers.(*NodeLeaseController).sync","file":"/workspace/pkg/kwok/controllers/node_lease_controller.go","line":270},"msg":"failed to update lease using latest lease","id":"kwok-controller-2-57f5bbf8c4-m5gm8_9e7f946d-c52a-45f5-8065-3fefd205f506","node":"kwok-node-263","err":"Operation cannot be fulfilled on leases.coordination.k8s.io \"kwok-node-263\": StorageError: invalid object, Code: 4, Key: /registry/leases/kube-node-lease/kwok-node-263, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: c7b6a56b-62cb-42e9-bed7-d0b2f114076a, UID in object meta: "}
{"time":"2023-07-06T02:30:57.619522822Z","level":"INFO","source":{"function":"sigs.k8s.io/kwok/pkg/kwok/controllers.(*NodeLeaseController).sync","file":"/workspace/pkg/kwok/controllers/node_lease_controller.go","line":267},"msg":"Syncing lease","id":"kwok-controller-2-57f5bbf8c4-m5gm8_9e7f946d-c52a-45f5-8065-3fefd205f506","node":"kwok-node-263"}
{"time":"2023-07-06T02:30:57.619818974Z","level":"ERROR","source":{"function":"sigs.k8s.io/kwok/pkg/kwok/controllers.(*NodeLeaseController).sync","file":"/workspace/pkg/kwok/controllers/node_lease_controller.go","line":270},"msg":"failed to update lease using latest lease","id":"kwok-controller-2-57f5bbf8c4-m5gm8_9e7f946d-c52a-45f5-8065-3fefd205f506","node":"kwok-node-263","err":"Operation cannot be fulfilled on leases.coordination.k8s.io \"kwok-node-263\": StorageError: invalid object, Code: 4, Key: /registry/leases/kube-node-lease/kwok-node-263, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: c7b6a56b-62cb-42e9-bed7-d0b2f114076a, UID in object meta: "}
{"time":"2023-07-06T02:30:57.619845545Z","level":"INFO","source":{"function":"sigs.k8s.io/kwok/pkg/kwok/controllers.(*NodeLeaseController).sync","file":"/workspace/pkg/kwok/controllers/node_lease_controller.go","line":267},"msg":"Syncing lease","id":"kwok-controller-2-57f5bbf8c4-m5gm8_9e7f946d-c52a-45f5-8065-3fefd205f506","node":"kwok-node-263"}
{"time":"2023-07-06T02:30:57.620394074Z","level":"ERROR","source":{"function":"sigs.k8s.io/kwok/pkg/kwok/controllers.(*NodeLeaseController).sync","file":"/workspace/pkg/kwok/controllers/node_lease_controller.go","line":270},"msg":"failed to update lease using latest lease","id":"kwok-controller-2-57f5bbf8c4-m5gm8_9e7f946d-c52a-45f5-8065-3fefd205f506","node":"kwok-node-263","err":"Operation cannot be fulfilled on leases.coordination.k8s.io \"kwok-node-263\": StorageError: invalid object, Code: 4, Key: /registry/leases/kube-node-lease/kwok-node-263, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: c7b6a56b-62cb-42e9-bed7-d0b2f114076a, UID in object meta: "}
{"time":"2023-07-06T02:30:57.620424533Z","level":"INFO","source":{"function":"sigs.k8s.io/kwok/pkg/kwok/controllers.(*NodeLeaseController).sync","file":"/workspace/pkg/kwok/controllers/node_lease_controller.go","line":267},"msg":"Syncing lease","id":"kwok-controller-2-57f5bbf8c4-m5gm8_9e7f946d-c52a-45f5-8065-3fefd205f506","node":"kwok-node-263"}
{"time":"2023-07-06T02:30:57.621266673Z","level":"ERROR","source":{"function":"sigs.k8s.io/kwok/pkg/kwok/controllers.(*NodeLeaseController).sync","file":"/workspace/pkg/kwok/controllers/node_lease_controller.go","line":270},"msg":"failed to update lease using latest lease","id":"kwok-controller-2-57f5bbf8c4-m5gm8_9e7f946d-c52a-45f5-8065-3fefd205f506","node":"kwok-node-263","err":"Operation cannot be fulfilled on leases.coordination.k8s.io \"kwok-node-263\": StorageError: invalid object, Code: 4, Key: /registry/leases/kube-node-lease/kwok-node-263, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: c7b6a56b-62cb-42e9-bed7-d0b2f114076a, UID in object meta: "}

### What did you expect to happen?

update node lease resource success

### How can we reproduce it (as minimally and precisely as possible)?

use the "in-cluster" method to create fake nodes.

### Anything else we need to know?

I think the issue is here.

https://github.com/kubernetes-sigs/kwok/blob/ef999cc2021f6d72439ed186483c94d5b01b8005/pkg/kwok/controllers/node_lease_controller.go#L351C1-L356C2

### Kwok version

kwok-v0.3.0

**Comment by wzshiming** [comment]
Thank you for your feedback

This update is intentional, e.g. in the case of multiple kwok controllers, only the controller that successfully renews the lease will maintain the node and the pods on it.

**Comment by isaac88** [comment]
Hello @wzshiming 
Is there a way to configure kwok-controller in high availability mode ? 
I mean, having 2 replicas at least running ?
Because if I put 2 at desired, the both pod/containers are crashing all the time.

**Comment by wzshiming** [comment]
> Is there a way to configure kwok-controller in high availability mode ?
I mean, having 2 replicas at least running ?

Support multiple replicas were added in 0.3, and [e2e has constantly been tested with multiple replicas](https://github.com/kubernetes-sigs/kwok/blob/1c12376e558e193af94e3bf8712b29b973db197f/test/kwok/kustomization.yaml#L16).

**Comment by isaac88** [comment]
Yes @wzshiming we use it(latest release) but when you set multiple replicas it starts to don't pass the readiness and liveness check, and it starts in a crashloopbackoff state.

**Comment by wzshiming** [comment]
Can you provide me with the kwok logs? I think there might be some clues in there.
