### ISSUE TITLE
Docs easily usage need

### ISSUE THREAD

**Issue by lowang-bh** [kubernetes-sigs/kwok#719]
### What would you like to be added?

After create kwok.yaml, and I need to create some pod stage with yaml, but errors occur.  I can not find the CRD or relative docs except https://kwok.sigs.k8s.io/docs/user/configuration/ or https://kwok.sigs.k8s.io/docs/generated/apis/#config.kwok.x-k8s.io/v1alpha1.KwokConfiguration. 
But there is no example about what should be configurated before use stage.
```
resource mapping not found for name: "pod-ready" namespace: "" from "example/pod-stage.yaml": no matches for kind "Stage" in version "kwok.x-k8s.io/v1alpha1"
ensure CRDs are installed first
```

### Why is this needed?

Make it more easy to use.

**Comment by wzshiming** [comment]
Support for CRD is in the 0.4 milestone and is currently not supported in the latest 0.3.

#264

**Comment by lowang-bh** [comment]
> Support for CRD is in the [0.4 milestone](https://github.com/kubernetes-sigs/kwok/milestone/4) (https://github.com/kubernetes-sigs/kwok/issues/264) and is currently not supported in the latest 0.3.

So pod stage is not released at current time(before 0.4 release), right? I see it in docs.

**Comment by wzshiming** [comment]
It's already available, but it's not a CRD, so you can only configure it with --config.

**Comment by lowang-bh** [comment]
> It's already available, but it's not a CRD, so you can only configure it with --config.

OK, I see it.  Now I want to apply this config file https://github.com/kubernetes-sigs/kwok/blob/main/test/lifecycle/fake-pod-stages.yaml, but don't know how to config it.

Do I need to put those contents in fake-pod-stages.yaml at the end of file `~/.kwok/clusters/kwok/kwok.yaml` ?

**Comment by wzshiming** [comment]
Specify the Stage file with --config, i.g. https://kwok.sigs.k8s.io/docs/examples/argo/

**Comment by lowang-bh** [comment]
I used the exist kind cluster and put stage.yaml at ~/.kwok/kwok.yaml. But there is no stage change when watch pods status.
```
kubectl apply -f  fake-pod-stage.yaml &&  kubectl get pod -o wide --watch
```
![image](https://github.com/kubernetes-sigs/kwok/assets/21003791/921a0e71-1900-407e-9960-e5772009ae50)

I want to watch the status changed like this.
https://kwok.sigs.k8s.io/docs/user/stages-configuration/

**Comment by wzshiming** [comment]
Changing the configuration of an already created cluster will not take effect, you need to recreate it. please look carefully at the example.

**Comment by wzshiming** [comment]
/close

Feel free to reopen if you have any other questions
