### ISSUE TITLE
Support get status of all clusters (stop or running) when execute 'kwokctl get clusters'

### ISSUE THREAD

**Issue by forgocode** [kubernetes-sigs/kwok#733]
### What would you like to be added?

When i execute 'kwokctl get clusters', i can know the status of every cluster.

### Why is this needed?

Like kubectl get node, i think kwokctl get clusters also need status(running or stop)

**Comment by wzshiming** [comment]
To do this, it may be necessary to split it into two items

- Implementing the ability to get detailed status information about individual clusters
- And then there's this, which displays abbreviated status information for each cluster in a list.

I don't have enough bandwidth, Let's add it to the milestone. 😄
