### ISSUE TITLE
KWOK sets pod status to "Completed" when running against volcano scheduler

### ISSUE THREAD

**Issue by dmitsh** [kubernetes-sigs/kwok#762]
### How to use it?

- [X] kwok
- [ ] kwokctl --runtime=docker (default runtime)
- [ ] kwokctl --runtime=binary
- [ ] kwokctl --runtime=nerdctl
- [ ] kwokctl --runtime=kind

### What happened?

When using volcano scheduler (github.com/volcano-sh/volcano), KWOK sets the pod status to "Completed", instead of keeping it "Running".

### What did you expect to happen?

The pod status should be "Running"

### How can we reproduce it (as minimally and precisely as possible)?

1. Deploy volcano scheduler
```bash
kubectl apply -f https://raw.githubusercontent.com/volcano-sh/volcano/release-1.7/installer/volcano-development.yaml
```

2. Deploy Volcano Job
```bash
cat <<EOF | kubectl apply -f -
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: test-job
spec:
  minAvailable: 1
  schedulerName: volcano
  policies:
    - event: PodEvicted
      action: RestartJob
  plugins:
    ssh: []
    env: []
    svc: []
  maxRetry: 5
  queue: default
  tasks:
    - replicas: 1
      name: "default-nginx"
      template:
        metadata:
          name: web
        spec:
          containers:
            - image: nginx
              imagePullPolicy: IfNotPresent
              name: nginx
              resources:
                requests:
                  cpu: "0.5"
          restartPolicy: OnFailure
          nodeSelector:
            type: kwok
EOF
```

3. Observe pod status
```bash
kubectl get po
NAME                       READY   STATUS      RESTARTS   AGE   IP           NODE            NOMINATED NODE   READINESS GATES
test-job-default-nginx-0   0/1     Completed   0          11s   10.244.9.0   kwok-1   <none>           <none>
```

### Anything else we need to know?

This issue does not happen if I use a virtual-kubelet to emulate the node

### Kwok version

I'm running kwok-controller inside k8s cluster
```bash
    spec:
      containers:
      - args:
        - --manage-all-nodes=false
        - --manage-nodes-with-annotation-selector=kwok.x-k8s.io/node=fake
        - --manage-nodes-with-label-selector=
        - --disregard-status-with-annotation-selector=kwok.x-k8s.io/status=custom
        - --disregard-status-with-label-selector=
        - --node-ip=$(POD_IP)
        - --node-port=10247
        - --cidr=10.0.0.1/24
        - --node-lease-duration-seconds=40
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        image: nvcr.io/nv-ngc-devops/kwok:v0.3.0
        imagePullPolicy: IfNotPresent
```

### OS version

<details>
```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Darwin:
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

**Comment by wzshiming** [comment]
Because it matches this rule, you can modify it to suit your needs.

https://kwok.sigs.k8s.io/docs/user/stages-configuration/

https://github.com/kubernetes-sigs/kwok/blob/3c6c48f0843f168cf053b2ffa71ddb03d07a95df/stages/pod-fast.yaml#L75-L84

**Comment by dmitsh** [comment]
So, how should I modify it, and where do I apply these changes if I run kwok-controller in an existing cluster?

**Comment by wzshiming** [comment]
On 0.3.0, you must mount the configuration in Kwok-controller.
The next release will support the CRD configuration, which is expected to be released next week.
