### ISSUE TITLE
kwokctl scale custom cluster

### ISSUE THREAD

**Issue by huiwq1990** [kubernetes-sigs/kwok#797]
### What would you like to be added?

`kwokctl scale` can scale node for custom clusters.

### Why is this needed?

Currently, kwokctl scale need to set cluster name flag. When I want to scale a cluster already exist, I want to paas kubeconfig file path.

**Comment by wzshiming** [comment]
I was planning to work on this, but suddenly realized that it might be dangerous to operate the existing cluster directly, do you have any special needs to do this?

**Comment by huiwq1990** [comment]
@wzshiming I want to use kwok for cluster pressure test, to find how many nodes the cluster can manage. So it's safe to delete test nodes.

**Comment by wzshiming** [comment]
We plan to add operators to meet these needs in the future.

#1126
#1122
