### ISSUE TITLE
[kwok] controller doesn't retry when the stage play runs into transient error

### ISSUE THREAD

**Issue by fuweid** [kubernetes-sigs/kwok#816]
### How to use it?

- [X] kwok
- [ ] kwokctl --runtime=docker (default runtime)
- [ ] kwokctl --runtime=binary
- [ ] kwokctl --runtime=nerdctl
- [ ] kwokctl --runtime=kind

### What happened?

```
{"time":"2023-10-16T02:35:26.331648934Z","level":"ERROR","source":{"function":"sigs.k8s.io/kwok/pkg/kwok/controllers.(*PodController).playStage","file":"/workspace/pkg/kwok/controllers/pod_controller.go","line":346},"msg":"Failed to patch node","id":"kwok-virtualnode-42_383d16ce-8002-4b33-8774-df7428be80b6","pod":"argo/stress-883-sleep-3884558001","node":"kwok-virtualnode-42","stage":"pod-init-container-completed","err":"Patch \"https://10.0.0.1:443/api/v1/namespaces/argo/pods/stress-883-sleep-3884558001/status\": read tcp 10.244.1.37:36720->10.0.0.1:443: read: connection reset by peer"}
```

When the controller has transient error, it won't retry the pod stage. So that the pod will be stuck at the current stage forever.

> NOTE: Typo s/node/pod at https://github.com/kubernetes-sigs/kwok/blob/db6cea86d35b03c3694bd332c7f92f4fe1a05f24/pkg/kwok/controllers/pod_controller.go#L346

### What did you expect to happen?

The controller should retry the next stage play until it's successful

### How can we reproduce it (as minimally and precisely as possible)?

1. apply normal pod and the stage will move the stage into completed after 5s.
2. before the next stage, restart the apiserver and let the controller hits the error
3. 

### Kwok version

v0.4.0

### OS version

 Linux ubuntu 5.15.0-1049-azure

**Comment by caozhuozi** [comment]
Hi, @wzshiming. I think the issue might be solved if we reput the resource into `preprocessChan` if an error occurs?

(The `delay` should be ignored for a retry.)

https://github.com/kubernetes-sigs/kwok/blob/db6cea86d35b03c3694bd332c7f92f4fe1a05f24/pkg/kwok/controllers/pod_controller.go#L345-L347

**Comment by wzshiming** [comment]
> Hi, @wzshiming. I think the issue might be solved if we reput the resource into `preprocessChan` if an error occurs?
> 
> (The `delay` should be ignored for a retry.)
> 
> https://github.com/kubernetes-sigs/kwok/blob/db6cea86d35b03c3694bd332c7f92f4fe1a05f24/pkg/kwok/controllers/pod_controller.go#L345-L347
> 
> What do you think?


It can cause other problems, such as it will keep retrying until apiserver hangs then kwok itself in a dead loop.


I was thinking of possibly adding a `retry` field to Stage to configure different retry policies based on different error types and Stage types.

**Comment by fuweid** [comment]
IMO, kwok should retry that error with timeout until that resource is being deleted. I think it is part of robustness. If add retry field on Stage, that means kwok can't guarantee lifecycle based on user's configuration.

**Comment by wzshiming** [comment]
@fuweid @caozhuozi 

I have a new idea, define a set in the controller, put all failed objects in it, and start a new thread to traverse it periodically until it is updated or deleted.

This ensures that the lifecycle is not interrupted and does not cause kwok or apiserver to crash.

What do you think?

**Comment by caozhuozi** [comment]
> @fuweid @caozhuozi
> 
> I have a new idea, define a set in the controller, put all failed objects in it, and start a new thread to traverse it periodically until it is updated or deleted.
> 
> This ensures that the lifecycle is not interrupted and does not cause kwok or apiserver to crash.
> 
> What do you think?

 Let me add more details:
1. move those failed objects into a separate set. 
2. start a new thread to handle the set periodically.
3. for each failed object, do re-match and re-apply. 
    3.1 the object will be removed from the set if it succeeds. 
    3.2 Otherwise, do nothing

Please correct me if i understand wrong.

I also have a question here:
If an event of the failed objects is received by the main thread, do we need to check whether the associated object already exists in the failed set and skip it?

**Comment by wzshiming** [comment]
> If an event of the failed objects is received by the main thread, do we need to check whether the associated object already exists in the failed set and skip it?

I think if the same object has new events coming in that indicate that it has been updated by another controller, it should be removed from the failed set.

**Comment by wzshiming** [comment]
There may also be a situation that should be considered, if the `nextTemplate` is misconfigured what should be the behavior?

What do you think?

**Comment by fuweid** [comment]
> There may also be a situation that should be considered, if an object is long-term stay in the failed set 

What about backoff retry? The longest retry is 5 minutes and log that reason why it fails.

**Comment by wzshiming** [comment]
> What about backoff retry? The longest retry is 5 minutes and log that reason why it fails. For kwok, Stage is also state machine to maintain lifecycle. Backoff retry sounds reasonable.

Sure, except for the 5 minute longest retry time which may need to be added.

Use a separate DelayingQueue for failed objects
- Move these failed objects to a separate failed queue.
- If the same object has new events coming in, they should be removed from the failed queue.
- start a new thread to handle the failed queue
  - If the retry succeeds, do nothing.
  - Otherwise, keep track of the number of retries and put them back into the failed queue.

**Comment by caozhuozi** [comment]
> > What about backoff retry? The longest retry is 5 minutes and log that reason why it fails. For kwok, Stage is also state machine to maintain lifecycle. Backoff retry sounds reasonable.
> 
> Sure, except for the 5 minute longest retry time which may need to be added.
> 
> Use a separate DelayingQueue for failed objects
> 
> * Move these failed objects to a separate failed queue.
> * If the same object has new events coming in, they should be removed from the failed queue.
> * start a new thread to handle the failed queue
>   
>   * If the retry succeeds, do nothing.
>   * Otherwise, keep track of the number of retries and put them back into the failed queue.

It looks much clearer. If possible, I'd like to try to take this issue~

**Comment by wzshiming** [comment]
Yep, please take it

**Comment by caozhuozi** [comment]
> > What about backoff retry? The longest retry is 5 minutes and log that reason why it fails. For kwok, Stage is also state machine to maintain lifecycle. Backoff retry sounds reasonable.
> 
> Sure, except for the 5 minute longest retry time which may need to be added.
> 
> Use a separate DelayingQueue for failed objects
> 
> * Move these failed objects to a separate failed queue.
> * If the same object has new events coming in, they should be removed from the failed queue.
> * start a new thread to handle the failed queue
>   
>   * If the retry succeeds, do nothing.
>   * Otherwise, keep track of the number of retries and put them back into the failed queue.

I'm a little confused now. an object should be removed from a failed queue based on  **retry times** or a **timeout**?

**Comment by wzshiming** [comment]
Let me clarify what the 3 worker threads do:

- Watch from Apiserver: When an object has a new event (e.g. modified by others), it is removed from the Failed Queue and placed in the Normal Queue.
- Internal Normal Queue: Take the object, try to complete it, its failures will be placed in the Failed Queue.
- Internal Failed Queue: Take the object, try to complete it, its failures will be placed in the Failed Queue, always retrying, each time the interval is double the previous one, until it reaches the maximum value, the interval will not be increased.
