### ISSUE TITLE
use kwok to simulate K8s cluster pod/node. deamonset status does not work fine

### ISSUE THREAD

**Issue by liyuerich** [kubernetes-sigs/kwok#826]
### How to use it?

- [X] kwok
- [ ] kwokctl --runtime=docker (default runtime)
- [ ] kwokctl --runtime=binary
- [ ] kwokctl --runtime=nerdctl
- [ ] kwokctl --runtime=kind

### What happened?

use kwok to simulate K8s cluster pod/node. check workload-deamonset， total should be 18, but it is 7. due to 11 is kwok node?

![image](https://github.com/kubernetes-sigs/kwok/assets/97269208/abfba8a0-f093-4e53-b5a9-ce796077a95b)

### What did you expect to happen?

hope deamonset status works as others

### How can we reproduce it (as minimally and precisely as possible)?

use kwok to simulate K8s cluster pod/node. create deamonset workload

### Kwok version

<details>

```console
$ kwok --version
# paste output here

$ kwokctl --version
# paste output here
v0.4.0

</details>


### OS version

<details>
```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Darwin:
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
k8s version 1.26.7
</details>

**Comment by liyuerich** [comment]
<img width="917" alt="image" src="https://github.com/kubernetes-sigs/kwok/assets/97269208/03edd21d-01d6-400e-81fa-b94a23578953">

**Comment by wzshiming** [comment]
Can you try setting the `spec.minReadySeconds` of daemon to 0 ?

https://github.com/kubernetes/kubernetes/blob/7d064812bb4ade2328d609c7083e26afc1c83adf/pkg/controller/daemon/daemon_controller.go#L1187
