### ISSUE TITLE
Support sync node status.images with pod

### ISSUE THREAD

**Issue by wzshiming** [kubernetes-sigs/kwok#839]
### What would you like to be added?

- Support sync node status.images with pod
- Add a flag to allow kwok-controller to enable this feature.

### Why is this needed?

Refinement of simulated kubelet behavior

**Comment by kevinmingtarja** [comment]
Hi, I'm interested to contribute to this feature.

Do you have any pointers on where to start? Thank you.

**Comment by wzshiming** [comment]
My idea would be to add a template function to [node template](
https://github.com/kubernetes-sigs/kwok/blob/ace628e8c2a152ec1f5d507cad1699db893b9e13/kustomize/stage/node/fast/node-initialize.yaml) that would look like this

``` yaml
images:
  {{ with NodeImages status.images }}
  {{ YAML . 1 }}
  {{ end }}
```

The `NodeImages` return will contain the `status.images` and the images used by the pods on this node.

**Comment by caozhuozi** [comment]
Hi, @wzshiming. Is the feature independent of `v1alpha2`?

**Comment by wzshiming** [comment]
https://github.com/kubernetes-sigs/kwok/issues/977#issuecomment-1951162145

I plan to add a new API that should cover this capability
