### ISSUE TITLE
Support increasing the etcd size limit

### ISSUE THREAD

**Issue by Sharpz7** [kubernetes-sigs/kwok#864]
### What would you like to be added?

See https://github.com/etcd-io/etcd/issues/15354#issuecomment-1669311470, this limit is not hard-imposed.

### Why is this needed?

For testing the limits of what etcd can do with Kubernetes, KWOK is a great base for a performance testing framework.

**Comment by wzshiming** [comment]
/assign @Sharpz7 

Thank you

**Comment by logica0419** [comment]
Since @Sharpz7 hasn't worked on this issue for months, I have opened the PR.
I hope Sharpz7 doesn't feel disgusted about this.
