### ISSUE TITLE
unsuitable certificate purpose

### ISSUE THREAD

**Issue by jeffguorg** [kubernetes-sigs/kwok#869]
### How to use it?

- [ ] kwok
- [X] kwokctl --runtime=docker (default runtime)
- [ ] kwokctl --runtime=binary
- [ ] kwokctl --runtime=nerdctl
- [ ] kwokctl --runtime=kind

### What happened?

I found that curl cannot visit kwok cluster even if i supplied --cacert.

```
curl --cacert ~/.kwok/clusters/kwok/pki/ca.crt http://127.0.0.1:<port>
curl: (60) SSL certificate problem: unsuitable certificate purpose
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

it works fine in kubeadm clusters like kind or production clusters.

### What did you expect to happen?

```
curl --cacert ~/.kwok/clusters/kwok/pki/ca.crt http://127.0.0.1:<port>
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "forbidden: User \"system:anonymous\" cannot get path \"/\"",
  "reason": "Forbidden",
  "details": {},
  "code": 403
}
```

### How can we reproduce it (as minimally and precisely as possible)?

just kwokctl create cluster, curl it (with openssl) or use rustls in rust, and you get it 

### Anything else we need to know?

i think it's extended key usage that causing this problem.

which is related to this line(or file): 
https://github.com/wzshiming/kwok/blob/df21672368ff9046c00c98d9e44bb225de7ab903/pkg/kwokctl/pki/pki.go#L109C30-L109C41

key usage and extended key usage might need to be specified according to https://kubernetes.io/zh-cn/docs/setup/best-practices/certificates/

### Kwok version

<details>

```console
$ kwok --version
kwok version v0.4.0 go1.21.4 (darwin/amd64)

$ kwokctl --version
kwokctl version v0.4.0 go1.21.4 (darwin/amd64)
```

</details>

### OS version

<details>
```console
# On Darwin:
$ uname -a
Darwin ChaodeMacBook-Pro 23.1.0 Darwin Kernel Version 23.1.0: Mon Oct  9 21:27:27 PDT 2023; root:xnu-10002.41.9~6/RELEASE_X86_64 x86_64 i386 Darwin
```
</details>

**Comment by wzshiming** [comment]
https://github.com/kubernetes-sigs/kwok/blob/681faa3e906fff3fd33c2ba72dca526a7bcbb171/pkg/kwokctl/pki/pki.go#L109

I tried adding ExtKeyUsageServerAuth here and it worked, but the ExtKeyUsageAny didn't work. it seems that the definition of ExtKeyUsageAny is not the same, so I went to raise an Issue for that and wait for it openssl/openssl#23049

**Comment by jeffguorg** [comment]
@wzshiming thanks for your support.

yes. it's weird. i found that there IS differences between golang and other certificate validation implementations(openssl rustls). just don't know how and why. so any kubernetes clients writen in go, like kubectl, is not affected.

maybe it's better to trace down how kubeadm generate certificates? i plan to do it in the next few days, if the issue is not resolved and nobody have better sugguestions.

**Comment by jeffguorg** [comment]
I believe that ext key usage is specified at [kubernetes/kubernetes certlist.go#L275C53-L275C53](https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/phases/certs/certlist.go#L275C53-L275C53)

<details>

```go
// KubeadmCertAPIServer is the definition of the cert used to serve the Kubernetes API.
func KubeadmCertAPIServer() *KubeadmCert {
	return &KubeadmCert{
		Name:     "apiserver",
		LongName: "certificate for serving the Kubernetes API",
		BaseName: kubeadmconstants.APIServerCertAndKeyBaseName,
		CAName:   "ca",
		config: pkiutil.CertConfig{
			Config: certutil.Config{
				CommonName: kubeadmconstants.APIServerCertCommonName,
				Usages:     []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth},
			},
		},
		configMutators: []configMutatorsFunc{
			makeAltNamesMutator(pkiutil.GetAPIServerAltNames),
		},
	}
}
```

</details>

key usage is configured at [pki_helpers.go#L632C1-L635C3](https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/util/pkiutil/pki_helpers.go#L632C1-L635C3)
<details>

```go
	keyUsage := x509.KeyUsageKeyEncipherment | x509.KeyUsageDigitalSignature
	if isCA {
		keyUsage |= x509.KeyUsageCertSign
	}
```

</details>

key usage & ext key usage is finally consumed by [NewSignedCert pki_helpers.go#L655C2-L655C2](https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/util/pkiutil/pki_helpers.go#L655C2-L655C2), where keyUsage is `x509.KeyUsageKeyEncipherment | x509.KeyUsageDigitalSignature | (isCA ? x509.KeyUsageCertSign: 0)` and ext key usage is simply `ExtKeyUsageServerAuth`

<details>

```go
	// certTmpl := x509.Certificate{
	// 	Subject: pkix.Name{
	// 		CommonName:   cfg.CommonName,
	// 		Organization: cfg.Organization,
	// 	},
	// 	DNSNames:              cfg.AltNames.DNSNames,
	// 	IPAddresses:           cfg.AltNames.IPs,
	// 	SerialNumber:          serial,
	// 	NotBefore:             caCert.NotBefore,
	// 	NotAfter:              notAfter,
		KeyUsage:              keyUsage,
		ExtKeyUsage:           cfg.Usages,
	// 	BasicConstraintsValid: true,
	// 	IsCA:                  isCA,
	// }
```

</details>

**Comment by jeffguorg** [comment]
kwokctl create one certificate for both apiserver and client, so not only server auth but also client auth need to be specified.

another way is specify both any and server auth according to https://github.com/kubernetes-sigs/kwok/pull/877#discussion_r1431112921 @wzshiming and i can verify that it works too.
