### ISSUE TITLE
[kwokctl] Support compress file as input and output

### ISSUE THREAD

**Issue by wzshiming** [kubernetes-sigs/kwok#885]
### What would you like to be added?

- Determine if the file is compressed based on the suffix `.gz`

### Why is this needed?

Importing and exporting files with yaml is too big

**Comment by Fish-pro** [comment]
@wzshiming

**Comment by wzshiming** [comment]
I have already done this [feature](https://github.com/wzshiming/kwok/commit/15ec1527f808c83c2dae7a6501aa881bcccc5eed) on #884

**Comment by Fish-pro** [comment]
> I have already done this [feature](https://github.com/wzshiming/kwok/commit/15ec1527f808c83c2dae7a6501aa881bcccc5eed) on #884

ok
