### ISSUE TITLE
The priority and relation of the fields in `next` of Stage need to be defined

### ISSUE THREAD

**Issue by caozhuozi** [kubernetes-sigs/kwok#890]
### How to use it?

- [X] kwok
- [ ] kwokctl --runtime=docker (default runtime)
- [ ] kwokctl --runtime=binary
- [ ] kwokctl --runtime=nerdctl
- [ ] kwokctl --runtime=kind

### What happened?

Currently, the priority and relation of the fields in `next` of a Stage are not well-defined. 

### What did you expect to happen?

It is necessary to have such a specification to guide the behavior of the controllers in `kwok`.

### How can we reproduce it (as minimally and precisely as possible)?

This is an issue for discussing.

### Kwok version

<details>
0.4.0
```console
$ kwok --version
# paste output here

$ kwokctl --version
# paste output here
```

</details>

### OS version

<details>
```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Darwin:
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

**Comment by caozhuozi** [comment]
`delete` that is true has higher priority than a non-empty `statusTemplate`, which means `kwok` will delete the resource rather than update its status if both are set. 

Apart from status update and resource deletion, there are also two fields in `next` that allow users to do some additional actions on a simulated resource before update or deletion.  `event` allows users to emit an associated Kubernetes event if there is a need to record something. `finalizers` allows users to add or remove finalizers. Please note that both of the two fields can exist on their own without being dependent on `delete` or ``statusTemplate` field. In this case, `kwok` will only send an event or modify finalizers and will not update status or delete a resource when applying a Stage.

**Comment by caozhuozi** [comment]
If any error occurs during applying a Stage, we should return immediately (and it will be retried. -> this involves another issue https://github.com/kubernetes-sigs/kwok/issues/816.)

**Comment by caozhuozi** [comment]
> If any error occurs during applying a Stage, we should return immediately (and it will be retried. -> this involves another issue #816.)

Hi @wzshiming, Could you help confirm this? If it is confirmed, I will raise a separate PR to first make the controller return immediately if any error occurs. This PR serves as a prerequisite for the retry feature and makes the logic more clearer.

**Comment by wzshiming** [comment]
I agree with you, refer to the [discussion of Slack](https://kubernetes.slack.com/archives/C04QPDWGW0M/p1703682608550159)
