### ISSUE TITLE
more general resource lifecycle simulation

### ISSUE THREAD

**Issue by caozhuozi** [kubernetes-sigs/kwok#921]
### What would you like to be added?

Power by `Stage`, `kwok` is now able to change the `status` of any resource type.

Can we  further loosen such restrictions such that we can even let `kwok` change other fields (like `spec`) in addtion to `status`?

### Why is this needed?

This makes `kwok` more complete in terms of resource lifecycle simulation.

**Comment by caozhuozi** [comment]
The feature is requested by a user in kwok WeChat Group.

**Comment by wzshiming** [comment]
This will be covered by #922.
