### ISSUE TITLE
Do we have document about how to  perform Resource usage simulation?

### ISSUE THREAD

**Issue by caozhuozi** [kubernetes-sigs/kwok#942]
### What would you like to be added?

Document how to perform resource usage simulation.

### Why is this needed?

Make the `kwok` documents more complete.

**Comment by wzshiming** [comment]
Not yet, it would be great if you could help with that.

My idea is a demo step like the following

```bash
kwokctl create cluster --enable-metrics-server -c ./kustomize/metrics/resource/metrics-resource.yaml -c ./kustomize/metrics/usage/usage-from-annotation.yaml
kwokctl scale node --replicas 2
kwokctl scale node --replicas 5

kubectl top pod

kubectl patch pod pod-000000 --type=json -p='[{"op": "add", "path": "/metadata/annotations", "value": {"kwok.x-k8s.io/usage-cpu": "100m", "kwok.x-k8s.io/usage-memory": "100Mi"}}]'

kubectl top pod
```

**Comment by caozhuozi** [comment]
Yes. I'm pleased to help document it.
Will discuss with you the details if I encounter any questions.

**Comment by wzshiming** [comment]
Hi @caozhuozi

I've made a rough draft #956, so you can leave a comment and add to it, or improve it in the future.

**Comment by caozhuozi** [comment]
> Hi @caozhuozi
> 
> I've made a rough draft #956, so you can leave a comment and add to it, or improve it in the future.

Hi @wzshiming ,
Can I update based on your current draft branch: [docs/metrics-resource-usage](https://github.com/wzshiming/kwok/tree/docs/metrics-resource-usage)?
