### ISSUE TITLE
Delayed stages sometimes not executed

### ISSUE THREAD

**Issue by bingzhang24** [kubernetes-sigs/kwok#958]
### How to use it?

- [X] kwok
- [ ] kwokctl --runtime=docker (default runtime)
- [ ] kwokctl --runtime=binary
- [ ] kwokctl --runtime=nerdctl
- [ ] kwokctl --runtime=kind

### What happened?

After upgrading to kwok 0.5.0 we noticed that quite often a delayed stage is scheduled but not executed at all on some pods.  The problem happens randomly. 

As shown in the attached log file (filtered by the pod name), a "delayed play stage" was created (line 11), which is supposed to update the pod status after 20 seconds, but no action was taken.  There was no error either.

Subsequent log messages "resource version not changed" seem to suggest that the deplayed job is still pending.

[kwok.log](https://github.com/kubernetes-sigs/kwok/files/14145984/kwok.log)

### What did you expect to happen?

Pod's status should be updated. The log message should include a line showing `Patch pod`. If the update failed, there should be error messages. 

### How can we reproduce it (as minimally and precisely as possible)?

The problem can be reproduced by submitting many pods that match some delayed stage.  It's more likely when several pods meet the selectors of the stage at roughly the same time.

Perhaps an easier way to reproduce is to create many pods or jobs, wait for them to complete, and then delete all of them at once.  On some pods the "pod-remove-finalizer" stage may be scheduled, but not executed, and as a result the pods will stuck at "Terminating".  The stage `pod-remove-finalizer` in [pod-general.yaml](stages/pod-general.yaml) can be used for this setup. 

### Anything else we need to know?

We have not noticed this behavior with v0.4.0.

### Kwok version

<details>

```console
$ kwok --version
kwok version v0.5.0 go1.21.4 (linux/amd64)

$ kwokctl --version
N/A. Not used. 
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.19.1
PRETTY_NAME="Alpine Linux v3.19"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://gitlab.alpinelinux.org/alpine/aports/-/issues"

$ uname -a

Linux kwok-controller-58c44867d5-prmhj 5.10.192-183.736.amzn2.x86_64 #1 SMP Wed Sep 6 21:15:41 UTC 2023 x86_64 Linux
```
</details>

**Comment by Huang-Wei** [comment]
It _might_ be a regression given it's not observed in v0.4.0.

**Comment by bingzhang24** [comment]
More information after I made some changes to the code to print out the `resourceVersion` of the current event, and `jobResourceVersion` for the queued job.   The example below shows that `pod-remove-finalizer` stage is cancelled due to a stale event but not recreated. 

Observations :

* Line 1:  A remove-finalizer stage is scheduled
* Line 2: Some other event (which appears to be stale) arrived, which caused the stage to be cancelled, according to https://github.com/kubernetes-sigs/kwok/blob/main/pkg/kwok/controllers/pod_controller.go#L244.  
* Line 3: Another event was processed, this time it has the same resource version as in Line 1, the latest resource version.  But https://github.com/kubernetes-sigs/kwok/blob/main/pkg/kwok/controllers/pod_controller.go#L234 produced a match, even though the stage was cancelled.   The result is that the stage is gone from the queue but an entry still remains in `delayQueueMapping`. 

I wonder if L244 is buggy.  Don't we need to remove the stage from `delayQueueMapping` when we cancel the job? 

As to why the events arrive out of order, that's another issue to investigate.

```
1 {"time":"2024-02-02T23:55:48.940373759Z","level":"DEBUG","source":{"function":"sigs.k8s.io/kwok/pkg/kwok/controllers.(*PodController).preprocess","file":"/Users/bing_zhang/dev/kwok/pkg/kwok/controllers/pod_controller.go","line":282},"msg":"Delayed play st
age","id":"kwok-controller-8f8fc5b9b-dz2fc_cbd91aa0-3043-40cf-b07b-3558fb4dda6a","pod":"default/fake-grouped-task-13bfada0-008-006","node":"kwok-node-staging-0020","delay":{"nanosecond":1000000000,"human":"1s"},"stage":"pod-remove-finalizer","resourceVers
ion":"813277424"}

2 {"time":"2024-02-02T23:55:48.998572005Z","level":"DEBUG","source":{"function":"sigs.k8s.io/kwok/pkg/kwok/controllers.(*PodController).preprocess","file":"/Users/bing_zhang/dev/kwok/pkg/kwok/controllers/pod_controller.go","line":250},"msg":"Stage cancelled
","id":"kwok-controller-8f8fc5b9b-dz2fc_cbd91aa0-3043-40cf-b07b-3558fb4dda6a","pod":"default/fake-grouped-task-13bfada0-008-006","node":"kwok-node-staging-0020","stage":"pod-remove-finalizer","resourceVersion":"813270987","jobResourceVersion":"813277424"}

3 {"time":"2024-02-02T23:55:48.999051061Z","level":"DEBUG","source":{"function":"sigs.k8s.io/kwok/pkg/kwok/controllers.(*PodController).preprocess","file":"/Users/bing_zhang/dev/kwok/pkg/kwok/controllers/pod_controller.go","line":269},"msg":"Skip pod","id":
"kwok-controller-8f8fc5b9b-dz2fc_cbd91aa0-3043-40cf-b07b-3558fb4dda6a","pod":"default/fake-grouped-task-13bfada0-008-006","node":"kwok-node-staging-0020","reason":"not match any stages","resourceVersion":"813270987"}

```

**Comment by wzshiming** [comment]
Thank you, you're right, this cancellation of a job has actually been guaranteed in the following, the [L244](https://github.com/kubernetes-sigs/kwok/blob/main/pkg/kwok/controllers/pod_controller.go#L244) really not necessary here and could cause the problem you're talking about.

https://github.com/kubernetes-sigs/kwok/blob/a92bbcd20b3e67e590162e54ea4d6713bd68ae58/pkg/kwok/controllers/pod_controller.go#L724-L730

I can't reproduce the problem in my environments, I build the `ghcr.io/wzshiming/kwok/kwok:v0.5.1-rc.1` base on #962, do you have time to test if this pr fixes the bug?

**Comment by bingzhang24** [comment]
Thank you for the quick fix. That looks good to me. I'm going to run some tests to verify. 

However, do you have any insight on what might have caused the out-of-order delivery of events? Why would the event in line 3 of the log -- which presumably contains a version of the pod that doesn't have `deletionTimestamp` -- appear after the pod was already being deleted.   To my understanding the events from a watch stream should be ordered after the initial listing operation, according to this: https://etcd.io/docs/v3.2/learning/api/#watch-streams.

**Comment by bingzhang24** [comment]
The fix works well. I haven't seen the problem since then. Thanks!
